### ISSUE TITLE
lxqt-session dumped core after upgrade to qt 5.15.10

### ISSUE THREAD

**Issue by thx1111** [lxqt/liblxqt#326] opened 2023-07-04 02:28 UTC
Arch Linux
linux 6.4.1.arch1-1
qt5-base 5.15.10+kde+r130-1
libqtxdg 3.11.0-2
lxqt-build-tools 0.13.0-1
lxqt-session 1.3.0-3

```
 Process 658 (lxqt-session) of user 1000 dumped core.

 Stack trace of thread 658:
 #0  0x00007f418b53ce05 n/a (libQt5Gui.so.5 + 0x13ce05)
 #1  0x00007f418b549e66 _ZN15QGuiApplication4fontEv (libQt5Gui.so.5 + 0x149e66)
 #2  0x00007f418b5f4a54 _ZN5QFontC1Ev (libQt5Gui.so.5 + 0x1f4a54)
 #3  0x00007f418c6bec43 _ZN17LXQtPlatformThemeC2Ev (libqtlxqt.so + 0x10c43)
 #4  0x00007f418c6bed4b n/a (libqtlxqt.so + 0x10d4b)
 #5  0x00007f418b5342e7 _ZN21QPlatformThemeFactory6createERK7QStringS2_ (libQt5Gui.so.5 + 0x1342e7)
 #6  0x00007f418b53e769 _ZN22QGuiApplicationPrivate25createPlatformIntegrationEv (libQt5Gui.so.5 + 0x13e769)
 #7  0x00007f418b53fa99 _ZN22QGuiApplicationPrivate21createEventDispatcherEv (libQt5Gui.so.5 + 0x13fa99)
 #8  0x00007f418b09b215 _ZN23QCoreApplicationPrivate4initEv (libQt5Core.so.5 + 0x29b215)
 #9  0x00007f418b53fb46 _ZN22QGuiApplicationPrivate4initEv (libQt5Gui.so.5 + 0x13fb46)
 #10 0x00007f418bd75b9e _ZN19QApplicationPrivate4initEv (libQt5Widgets.so.5 + 0x175b9e)
 #11 0x00007f418c67e048 _ZN4LXQt11ApplicationC1ERiPPc (liblxqt.so.1 + 0x27048)
 #12 0x000055c4ae67c07e n/a (lxqt-session + 0xb07e)
 #13 0x00007f418a839850 n/a (libc.so.6 + 0x23850)
 #14 0x00007f418a83990a __libc_start_main (libc.so.6 + 0x2390a)
 #15 0x000055c4ae67ce35 _start (lxqt-session + 0xbe35)

 Stack trace of thread 669:
 #0  0x00007f418a913c0f __poll (libc.so.6 + 0xfdc0f)
 #1  0x00007f418ad6da9f n/a (libglib-2.0.so.0 + 0xb7a9f)
 #2  0x00007f418ad0e032 g_main_context_iteration (libglib-2.0.so.0 + 0x58032)
 #3  0x00007f418b0ea5cc _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2ea5cc)
 #4  0x00007f418b09a484 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x29a484)
 #5  0x00007f418aef72b6 _ZN7QThread4execEv (libQt5Core.so.5 + 0xf72b6)
 #6  0x00007f418c3a8a9a n/a (libQt5DBus.so.5 + 0x18a9a)
 #7  0x00007f418aef34da n/a (libQt5Core.so.5 + 0xf34da)
 #8  0x00007f418a89d44b n/a (libc.so.6 + 0x8744b)
 #9  0x00007f418a920e40 n/a (libc.so.6 + 0x10ae40)
 ELF object binary architecture: AMD x86-64
```

**Comment by tsujan** [comment] 2023-07-04 03:12
Not reproducible with git LXQt and with the same version of `qt5-base`.

Keeping it open for now, in case someone wants to add more info...

**Comment by thx1111** [comment] 2023-07-04 14:19
Hmm - I updated the software on another machine, and had no problem starting LXQt.  The machine with the problem is an older laptop with an Intel Core 2 Duo processor and Radeon graphics.

This seems tricky.  I don't know whether to blame the compiler, the C libs, the Qt libs, LXQt, or some uninitialized pointer somewhere.  Any suggestions about how to track the problem, looking at the stack trace?

**Comment by yan12125** [comment] 2023-07-06 09:39
See https://wiki.archlinux.org/title/Core_dump and https://wiki.archlinux.org/title/Debugging/Getting_traces. A stack trace with source filenames, line numbers and function arguments is better for diagnosis.

**Comment by thx1111** [comment] 2023-07-12 16:38
I've only just noticed that the problem with starting LXQt is directly related to interaction with SDDM, the Simple Desktop Display Manager.  On the laptop machine, LXQt is started by `sddm`, and on the desktop machine, using `startx`.  Starting LXQt on the laptop with `startx` works fine.  I can poke-around more on this as time permits.  Currently, I have sddm 0.20.0-1, a recent upgrade as of 2023-06-23.  See: https://github.com/sddm/sddm/blob/develop/ChangeLog

**Comment by tsujan** [comment] 2023-07-12 16:50
> ... is directly related to interaction with SDDM.... Currently, I have sddm 0.20.0-1

It can't be about SDDM; I have its version 0.20.0-1 too.

Please attach a clean backtrace, as @yan12125 mentioned.

**Comment by thx1111** [comment] 2023-07-12 23:20
[gdbTrace.txt](https://github.com/lxqt/liblxqt/files/12034039/gdbTrace.txt)
```
#0  0x00007f80e333ce05 in initFontUnlocked () at kernel/qguiapplication.cpp:249
```

**Comment by tsujan** [comment] 2023-07-13 13:08
It looks like a basic problem somewhere outside LXQt.

**Comment by stefonarch** [comment] 2024-05-01 16:20
As we are using Qt6 now closing this.

**Closed by stefonarch** 2024-05-01 16:20 UTC
