### ISSUE TITLE
Building fails in debian

### ISSUE THREAD

**Issue by iamthesenate1** [lxqt/liblxqt#298] opened 2021-10-30 14:56 UTC
##### Expected Behavior

liblxqt should build
##### Current Behavior

it doesn't 

Here is the log:
```Building: liblxqt using externally specified options: -DCMAKE_BUILD_TYPE=debug   

-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Building liblxqt with Qt 5.15.2
-- 
-- liblxqt version: 0.17.0
-- 
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xss_LIB (ADVANCED)
    linked by target "lxqt" in directory /home/debian/lxqt/liblxqt

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
I must also mention that I have libxss1 installed. The system runs Debian Sid

**Comment by tsujan** [comment] 2021-10-30 15:14
This is a Debian-specific question, not a bug report. It belongs to [Discussions](https://github.com/lxqt/lxqt/discussions) -> Q&A.

Make sure you've installed all required dev packages. I close this but comments can be added to it. You could also open a page at Discussions.

**Closed by tsujan** 2021-10-30 15:14 UTC
